server:
    #port: ${random.int[8001,8999]}
    port: 8001
    max-http-header-size: 20971520
    connection-timeout: 15000
    tomcat:
        max-threads: 500
        max-connections: 1000
        accept-count: 500
        #post
        max-http-post-size: 20971520

#context:
#  listener:
#    classes: com.viptail.biz.family.listener.FamilyServiceStartupListener

spring:
    application:
        name: fyy-service
     # freemarker routing
    #freemarker:
    #    template-loader-path: classpath:/templates
    #    suffix: .ftl
    #    charset: UTF-8
    # static file
    mvc:
        static-path-pattern: /static/**
    # mysql
    datasource:
        name: test
        url: jdbc:mysql://localhost:3306/fyyservice?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=true&allowMultiQueries=true&serverTimezone=Asia/Hong_Kong
        username: root
        password: root
        #
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        druid:
          filters: stat,log4j2
          filter:
            log4j2:
             statement-executable-sql-log-enable: true
             statement-sql-pretty-format: true
             enabled: true
          max-active: 200
          initial-size: 50
          max-wait: 60000
          min-idle: 1
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          validation-query: select 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          pool-prepared-statements: true
          max-open-prepared-statements: 200
          connection-init-sqls: set names utf8mb4;

#mybatis
mybatis:
    config-location: classpath:mybatis-config.xml
    mapperLocations: classpath:mybatis/*.xml
    typeAliasesPackage: com.shelly.fyyservice.pojo
    type-handlers-package: